version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ms-reservation-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reservation_db
    ports:
      - "3306:3306"
      - "33060:33060"

  ms-reservation:
    build: ../build/generated/sources/annotationProcessor/java/main
    container_name: ms-reservation-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reservation_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root